theme: minima

title: Arpitha's Blog
author: Arpitha Murthy
email: 
url: https://arpithamurthy.net

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >
  My first blog.

# Minima variables
#twitter_username:  arpithadmurthy
github_username:   arpithamurthy
linkedin_username: arpithadmurthy
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  Resume:          #
  LinkedIn:        https://www.linkedin.com/in/arpithadmurthy/
  GitHub:          https://github.com/arpithamurthy
  X:               https://x.com/Arpithadmurthy
  Website:         https://arpithamurthy.net

# plugin: jekyll-seo-tag
twitter:
  username: arpithadmurthy
  card: summary_large_image
social:
  name: Arpitha Murthy
  links:
    - https://x.com/arpithadmurthy
    - https://linkedin.com/in/arpithadmurthy
    - https://github.com/arpithamurthy

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: arpithamurthy/arpithamurthy.github.io

defaults:
  - scope:
      path: ""
    values:
      image: "" # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
